#!/usr/bin/env bash
set -euo pipefail

# ─── Container Watchdog Installer ───────────────────────────────────
# TASK-0045-A1: Mini macOS 容器自愈守护
# 基于 TASK-0043 LaunchAgent 模式，守护 allowlist 容器
# ────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GOVERNANCE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TEMPLATE="${GOVERNANCE_ROOT}/launchagents/com.botquant.container_watchdog.plist"
TARGET_DIR="${HOME}/Library/LaunchAgents"
TARGET_PLIST="${TARGET_DIR}/com.botquant.container_watchdog.plist"
RUNTIME_DIR="${HOME}/jbt-governance"
RUNTIME_SCRIPTS="${RUNTIME_DIR}/scripts"
RUNTIME_LOGS="${RUNTIME_DIR}/logs"
RUNTIME_LOCKS="${RUNTIME_DIR}/locks"
WATCHDOG_SCRIPT="${RUNTIME_SCRIPTS}/container_watchdog.sh"
LOG_PATH="${RUNTIME_LOGS}/container_watchdog.log"
LABEL="com.botquant.container_watchdog"
DOMAIN="gui/$(id -u)"

# ─── Allowlist（编辑此处增删受守护容器）───
ALLOWLIST=(
    "botquant-data"
    "JBT-SIM-TRADING-WEB-3002"
)

# ─── Validate ───
if [[ ! -f "${TEMPLATE}" ]]; then
    echo "ERROR: plist template not found: ${TEMPLATE}" >&2
    exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
    echo "ERROR: docker not found in PATH" >&2
    exit 1
fi

# ─── Create directories ───
mkdir -p "${TARGET_DIR}" "${RUNTIME_SCRIPTS}" "${RUNTIME_LOGS}" "${RUNTIME_LOCKS}"

# ─── Generate watchdog script ───
{
    echo '#!/usr/bin/env bash'
    echo '# Container Watchdog — allowlist-only recovery'
    echo '# Generated by install_container_watchdog.sh'
    echo '# DO NOT EDIT — re-run installer to update'
    echo ''
    echo 'ALLOWLIST=('
    for c in "${ALLOWLIST[@]}"; do
        echo "    \"${c}\""
    done
    echo ')'
    echo "LOCK_DIR=\"${RUNTIME_LOCKS}\""
    echo 'COOLDOWN=120'
    echo ''
    cat <<'INLINE'
for container in "${ALLOWLIST[@]}"; do
    status=$(docker inspect --format='{{.State.Status}}' "$container" 2>/dev/null || echo "not_found")
    if [[ "$status" != "running" ]]; then
        lock_file="${LOCK_DIR}/${container}.recovering"
        if [[ -f "$lock_file" ]]; then
            lock_age=$(( $(date +%s) - $(stat -f %m "$lock_file") ))
            if (( lock_age < COOLDOWN )); then
                echo "$(date '+%Y-%m-%d %H:%M:%S') SKIP ${container} (cooldown, age=${lock_age}s)"
                continue
            fi
        fi
        echo "$(date '+%Y-%m-%d %H:%M:%S') RECOVER ${container} (status=${status})"
        touch "$lock_file"
        docker start "$container" 2>&1 || echo "$(date '+%Y-%m-%d %H:%M:%S') FAIL ${container}"
    fi
done

# Clean stale locks for running containers
for container in "${ALLOWLIST[@]}"; do
    lock_file="${LOCK_DIR}/${container}.recovering"
    if [[ -f "$lock_file" ]]; then
        status=$(docker inspect --format='{{.State.Status}}' "$container" 2>/dev/null || echo "not_found")
        if [[ "$status" == "running" ]]; then
            rm -f "$lock_file"
        fi
    fi
done
INLINE
} > "${WATCHDOG_SCRIPT}"

chmod +x "${WATCHDOG_SCRIPT}"
echo "watchdog script generated: ${WATCHDOG_SCRIPT}"

# ─── Render plist template ───
TEMPLATE_PATH="${TEMPLATE}" \
TARGET_PATH="${TARGET_PLIST}" \
WATCHDOG_SCRIPT_VALUE="${WATCHDOG_SCRIPT}" \
HOME_VALUE="${HOME}" \
LOG_PATH_VALUE="${LOG_PATH}" \
python3 - <<'PYEOF'
import os
from pathlib import Path

template = Path(os.environ["TEMPLATE_PATH"]).read_text(encoding="utf-8")
rendered = (
    template
    .replace("__WATCHDOG_SCRIPT__", os.environ["WATCHDOG_SCRIPT_VALUE"])
    .replace("__HOME__", os.environ["HOME_VALUE"])
    .replace("__LOG_PATH__", os.environ["LOG_PATH_VALUE"])
)
Path(os.environ["TARGET_PATH"]).write_text(rendered, encoding="utf-8")
PYEOF

plutil -lint "${TARGET_PLIST}" >/dev/null
echo "plist rendered and validated: ${TARGET_PLIST}"

# ─── Install LaunchAgent ───
launchctl enable "user/$(id -u)/${LABEL}" >/dev/null 2>&1 || true
launchctl enable "${DOMAIN}/${LABEL}" >/dev/null 2>&1 || true

if launchctl print "${DOMAIN}/${LABEL}" >/dev/null 2>&1; then
    launchctl bootout "${DOMAIN}/${LABEL}" >/dev/null 2>&1 || true
    for _ in 1 2 3 4 5 6 7 8 9 10; do
        if ! launchctl print "${DOMAIN}/${LABEL}" >/dev/null 2>&1; then
            break
        fi
        sleep 1
    done
fi

if launchctl print "${DOMAIN}/${LABEL}" >/dev/null 2>&1; then
    launchctl kickstart -k "${DOMAIN}/${LABEL}"
else
    launchctl bootstrap "${DOMAIN}" "${TARGET_PLIST}"
fi

echo ""
echo "=== Container Watchdog Installed ==="
echo "label      = ${LABEL}"
echo "plist      = ${TARGET_PLIST}"
echo "script     = ${WATCHDOG_SCRIPT}"
echo "log        = ${LOG_PATH}"
echo "interval   = 60s"
echo "cooldown   = 120s"
echo "containers:"
for c in "${ALLOWLIST[@]}"; do
    echo "  - ${c}"
done
